# Generated by Django 4.1.4 on 2022-12-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_image_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(error_messages={'required': 'Please Enter your Name'}, max_length=200),
        ),
    ]
