# Generated by Django 4.1.4 on 2022-12-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='company_description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='company_name',
            field=models.CharField(max_length=20),
        ),
    ]
