# Generated by Django 4.1.4 on 2022-12-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_image_company_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='company_description',
            field=models.TextField(max_length=50),
        ),
    ]
