# Generated by Django 4.1.4 on 2022-12-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_image_company_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.TextField(max_length=100)),
                ('IsPublic', models.BooleanField()),
            ],
        ),
    ]
