# Generated by Django 4.1.4 on 2023-01-04 06:14

from django.db import migrations, models
import myapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='company_image',
            field=models.ImageField(upload_to='generate_unique_filename', validators=[myapp.validators.validate_image]),
        ),
    ]
