# Generated by Django 4.1.4 on 2022-12-28 07:41

from django.db import migrations, models
import myapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='company_image',
            field=models.ImageField(upload_to='myimage', validators=[myapp.validators.validate_image]),
        ),
    ]
